name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-check:
    name: Build Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Build and verify
        run: |
          deno fmt --check
          deno task check
          deno task build
          deno task verify
